### PR TITLE
[Technical-Support] AUI-1893 Wrong display of recurrent overnight events in week view in the last day of first week under DST

### PR DESCRIPTION
**Pull request by mairatma**
Hi Maira,

We have again a new Scheduler issue :)

I documented this issue in AUI-1893 ticket. Please see my attached screens and my new test cases.

I had another idea regarding this fix. We could made a new method in DateMath which will be responsible for handle Date objects with different Timezones.

Thanks in advance,
 Zsaga

### CODE REVIEW

**Comment by mairatma** [comment]
Hey @brandizzi, I've received this pr fixing a timezone bug on scheduler, so I'd really appreciate it if you could take a look at it too, since I trust your knowledge of these problems very much.

It's similar to a bug you've fixed in the past, but @zsagia is fixing and testing it differently, so could you take a look and check if that solves it as well?

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
We are having to merge this pull request. It used to consistently fail at some specific time zones (e.g. `America/Sao_Paulo`). After changing it to use `A.DataType.DateMath.countDays()`, it passes on Chrome but keeps failing at Firefox. The reasons behind it were documented on [a blog post](https://www.liferay.com/web/adam.brandizzi/blog/-/blogs/the-midnightless-midnight) and so far I'm trying to figure out how to deal with it. (Contrary to what I've stated in the blogs, my first approach did not work.)

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
